### ISSUE TITLE
Recording Assets

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#28]
Since we're going to do recordings again at the next meetup, I've been working on the necessary assets.
I'd like some feedback on the following:
[Intro](http://babelmonkeys.de/~florob/rustmcb/intro.mp4)
[Backdrop](http://babelmonkeys.de/~florob/rustmcb/background.svg) (slides and camera are overlayed on this)
[Outro](http://babelmonkeys.de/~florob/rustmcb/outro.mp4)

**Comment by colin-kiegel** [comment]
I like the Intro fade. I would consider to make it a bit more surprising maybe - something like 3s black, 1s fade, 1s orange?
Outro is cool too - I wouldn't change much - maybe you could try 1s orange 1s fade, 3s black (instead of instant fade) - or just leave it as is.
Backdrop: maybe alternating lines - one line rust logos, one line rust cologne logos?

These are just ideas, since you specifically asked for feedback. I already like your assets as they are. :-)

**Comment by colin-kiegel** [comment]
PS: It might be easier to judge the timings if you could render a very small demo video - maybe with some 10s dummy content (e.g. random old recording, or static picture)?

**Comment by killercup** [comment]
Very cool! I like the color fade—having the rotation and the fade at the same time makes it feel like a dimmer switch.

**Comment by Florob** [comment]
I've added a short pause before the animation in intro and outro. I think it's important to have the image static for a while at the end, so that people are not distracted from reading the information. Both are 1s static, 1s animation, 3s static now. I've also made a short demo putting them in context.
It would also make me feel more comfortable if someone double checked my spelling in the intros.

* [Intro Slack](http://babelmonkeys.de/~florob/rustmcb/review/17031.mp4)
* [Intro Diesel](http://babelmonkeys.de/~florob/rustmcb/review/17032.mp4)
* [Outro](http://babelmonkeys.de/~florob/rustmcb/review/outro.mp4)
* [Demo](http://babelmonkeys.de/~florob/rustmcb/review/demo.mp4)

**Comment by badboy** [comment]
I like it. Proof-read as well!
