### ISSUE TITLE
Save-The-Date Invitations

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#5]
We use to send only ONE invitation before a meetup. This has often been delayed, because we waited for the final agenda or tweaked the text, etc. 

I suggest to send the invitations in two steps:
1. An early / preliminary "save-the-date" invitation without any "dependencies" on agenda, etc. We shouldn't fiddle to much with this text - but instead send it as quickly as possible. Ideally the day after the previous meetup. The most important information is the date and the opportunity to start a discussion (on meetup, or elsewhere).
2. A final invitation 1-2 weeks before the meetup with an agenda (or alternatively cancellation or change-of-date).

@Florob @badboy @killercup What do you think?

**Comment by killercup** [comment]
Sounds good to me. I'd really like to pin down the actual dates when we do this.

We should make the first announcements as short as possible (maybe even with the exact same text each time), so it's clear this is just a "save the date" thing. This one should always be send out at least 4 weeks before the next meetup, e.g., the day after the last meetup.

For the second invitation I'd suggest we send it as soon as
- the final agenda is known,
- or it's the Monday of the week before the meetup.

We can always send out more emails with refinements to the agenda, but I don't think that's really necessary (and it might bother people, since meetup.com seems to send out semi-random reminder emails anyway).

**Comment by colin-kiegel** [comment]
decision accepted
