### ISSUE TITLE
Meeting in 2021

### ISSUE THREAD

**Issue by cars10** [Rustaceans/rust-cologne#93]
Hi, what do you think about having a meeting this year? We could define a maximum number of participants, 2G, etc.

**Comment by mre** [comment]
I'm all for it at least, but I'm not an organizer. 😉

**Comment by uwearzt** [comment]
Would also like to have a Meetup. We have to use the rooms at C4, the Cisco Office we used once is no longer available (and i don't work for Cisco any more). But AFAIK C4 is still closed for nonmembers (I am member of CCC but not the Cologne chapter).

**Comment by Florob** [comment]
I'll try to be honest here. For probably more than a year before the pandemic I effectively acted as the sole organizer. During that time it was mostly stress and very little enjoyment on my part. Partially because very few people ever offered up topics or content, and most of those that did ended up standing me up. Not the nicest position to be in when all eyes are on you.
So the pandemic was admittedly a very welcome change of pace, and that is the main reason I never pursued online meetups.

#94 has forced me to actually sit down an think about whether I want to continue running the meetup at some point, which I've admittedly avoided until now. I've come to the conclusion that fundamentally I do think this meetup should continue existing, and I would help organize it in some capacity. But for my own mental health I don't really want to be the sole person responsible any longer.

So here is my offer: The next meeting would not be a meetup, but one for/of (potential) new organizers. Obvious candidates are those that have attended the meetup for a long time. @mre, @uwearzt and @kawogi (I think, handle seems to have changed) come to mind, but I don't want to gate keep this role. We'd probably do that online, beginning of November.

To be transparent about the situation at the C4: The space is indeed still closed to non-members. However, it is open to meetups with one trusted organizer (i.e. a C4 member) under 2G rules.

**Comment by uwearzt** [comment]
I do not work in Cologne any more (i live near Düsseldorf), so it is not possible for me to be the organizer at the moment. I am also not a member of the C4 chapter (but a CCC member). 

But i would love to have a meetup near me (i always enjoyed the Meetups).

**Comment by mre** [comment]
Thanks for raising these concerns @Florob.
We should definitely have an online meeting about the topic soon.
I live in Düsseldorf, so organizing the meetup in Cologne would be difficult for me as well. That said, the C4 feels like the perfect venue for the meetup and like @uwearzt I loved going there.
Finding another (permanent) venue will be difficult. The better option would be to find someone close to Cologne who would be willing to fill the gap. I currently can't think of better alternatives.

**Comment by kawogi** [comment]
First off: sorry for that huge delay!

Due to lack of free time I've been hesitating to make a decision for myself. Also, organizing other people isn't exactly what I'm good at but I'd love to see the the meetups take place again. I just negotiated with my employer and they agreed to donate some of my working hours for being able to handle organizational stuff in that matter. They also might cover some minor fees for services that can be proven to be useful. 

That being said: what steps would be necessary to revive the Rust User Group Cologne Meetups? My guesses:

- [ ] Settle for a date/schedule/location (COVID-19 measures)
- [ ] Make a decision on how to invite members (esp. clarifying the role of meetup.com)
- [ ] Handing over credentials for accessing necessary tools/infrastructure (`rust.cologne`, `meetup.com`, …)
- [ ] Find a back-up strategy for times where I'm not available.
- [ ] Define a _format_ for our meetups

Sorry for going like a bull at the gate but I'd like to utilize my current boost of motivation :)

**Comment by kawogi** [comment]
@Florob What's the current situation for the C4? Still requiring a member-organizer under 2G as by https://github.com/Rustaceans/rust-cologne/issues/93#issuecomment-949358662 ?

At the moment I'm in Cologne every **Tuesday** and **Thursday** so these would be my favorite days to hold a meetup. I could imagine to have one virtual meetup and one with physical presence each month.

**Comment by Florob** [comment]
@kawogi Thanks for stepping up.
I can't claim my delay is much better, in terms of organizing something for potential new organizers. I was quite dissuaded by the comments here. It's not like I live in Cologne either, or have a reliable way to always be present on time.

The C4 is open to meetups again. The policy is pretty much "use common sense". The only other meetup that is slowly starting back up at the C4 is still enforcing 2G according to their announcement (that might be stale information though).
Unfortunately Tuesday and Thursday are the only days that won't really work. Tuesday is a closed assembly. Thursday is eventually (i.e. not yet) going to be open to the general public, leaving little space for a meetup.

In the spirit of using available motivation, shall we do an online meetup the week of June 20th? My suggestion would be doing part regular meetup (I'd actually like to talk about inline assembly again now that it hit stable), and part discussion about the future of the meetup (giving more people the opportunity to step up, maybe gather some input, general planning).

**Comment by kawogi** [comment]
Sounds good to me, even though I was hoping to start earlier this month. But maybe this gives us time to gather enough people to make your talk a little more attended.
June 20th … 24th are good for me. (22th still has a question mark). Around 19:00?

Do we have a kind-of-established platform for an online meetup? I remember a meetup held on `gather.town`. My personal default would be Jitsi.

(shall we rename this issue to "2022", start a new one or _don't care_?)

**Comment by Florob** [comment]
> Do we have a kind-of-established platform for an online meetup? I remember a meetup held on gather.town. My personal default would be Jitsi.

Big Blue Button is what I'm currently most used to. I'll confirm that/if we have a room on an instance available. Otherwise Jitsi is fine with me too. I don't really like `gather.town` or work adventure-style platforms for structured meetups. It lends itself better to more open formats (e.g. open space).

Let's try to go back to regular per-meetup issues. Closing in favor of #95.
